<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>GHS3D_ADV_ARGS</source>
      <translation>高度な</translation>
    </message>
    <message>
      <source>GHS3D_HYPOTHESIS</source>
      <translation>GHS3D</translation>
    </message>
    <message>
      <source>GHS3D_OPTIMIZATIOL_LEVEL</source>
      <translation>最適化のレベル</translation>
    </message>
    <message>
      <source>GHS3D_PERMISSION_DENIED</source>
      <translation>作業ディレクトリが書き込み可能ではないです。</translation>
    </message>
    <message>
      <source>GHS3D_STD_ARGS</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>GHS3D_TITLE</source>
      <translation>仮説構築</translation>
    </message>
    <message>
      <source>GHS3D_TO_MESH_HOLES</source>
      <translation>メッシュに穴します。</translation>
    </message>
    <message>
      <source>INIT_MEMORY_SIZE</source>
      <translation>初期メモリのサイズ</translation>
    </message>
    <message>
      <source>KEEP_WORKING_FILES</source>
      <translation>作業ファイルを維持するには</translation>
    </message>
    <message>
      <source>LEVEL_NONE</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>LEVEL_LIGHT</source>
      <translation>光</translation>
    </message>
    <message>
      <source>LEVEL_MEDIUM</source>
      <translation>中 (標準)</translation>
    </message>
    <message>
      <source>LEVEL_STANDARDPLUS</source>
      <translation>標準的です +</translation>
    </message>
    <message>
      <source>LEVEL_STRONG</source>
      <translation>強力な</translation>
    </message>
    <message>
      <source>MAX_MEMORY_SIZE</source>
      <translation>最大メモリ サイズ</translation>
    </message>
    <message>
      <source>MEGABYTE</source>
      <translation>メガバイト</translation>
    </message>
    <message>
      <source>NO_INITIAL_CENTRAL_POINT</source>
      <translation>初期の中心点を削除するには</translation>
    </message>
    <message>
      <source>RECOVERY_VERSION</source>
      <translation>境界の回復のバージョンを使用するには</translation>
    </message>
    <message>
      <source>FEM_CORRECTION</source>
      <translation>有限要素法による補正を使用するには</translation>
    </message>
    <message>
      <source>GHS3D_GRADATION</source>
      <translation>Volumic グラデーション</translation>
    </message>
    <message>
      <source>SELECT_DIR</source>
      <translation>...</translation>
    </message>
    <message>
      <source>TEXT_OPTION</source>
      <translation>オプション テキストとして</translation>
    </message>
    <message>
      <source>TO_ADD_NODES</source>
      <translation>新しいノードを作成するには</translation>
    </message>
    <message>
      <source>VERBOSE_LEVEL</source>
      <translation>詳細レベル</translation>
    </message>
    <message>
      <source>WORKING_DIR</source>
      <translation>作業ディレクトリ</translation>
    </message>
    <message>
      <source>GHS3D_ENFORCED_VERTICES</source>
      <translation>適用された頂点</translation>
    </message>
    <message>
      <source>GHS3D_ENFORCED_MESHES</source>
      <translation>強制メッシュ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_NAME_COLUMN</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_X_COLUMN</source>
      <translation>X</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Y_COLUMN</source>
      <translation>Y</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Z_COLUMN</source>
      <translation>Z</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SIZE_COLUMN</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_ENTRY_COLUMN</source>
      <translation>頂点のエントリ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_COLUMN</source>
      <translation>制約</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_COMPOUND_COLUMN</source>
      <translation>化合物</translation>
    </message>
    <message>
      <source>GHS3D_ENF_GROUP_COLUMN</source>
      <translation>グループ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SELECT_VERTEX</source>
      <translation>頂点を選択します</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SELECT_MESH</source>
      <translation>メッシュを選択します。</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_X_LABEL</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Y_LABEL</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Z_LABEL</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_LABEL</source>
      <translation>制約:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_NODE</source>
      <translation>ノード</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_EDGE</source>
      <translation>エッジ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_FACE</source>
      <translation>直面しています。</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SIZE_LABEL</source>
      <translation>サイズ:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_GROUP_LABEL</source>
      <translation>グループ:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_ADD</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>GHS3D_ENF_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_INFO</source>
      <translation>&lt;b&gt;警告&lt;/b&gt;: 強制頂点は現在関連付けられているジオメトリ w/o メッシュののみ考慮します。</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_INFO</source>
      <translation>&lt;b&gt;警告&lt;/b&gt;: 現在適用されたメッシュはメッシュ関連付けられたジオメトリなしののみ考慮します。</translation>
    </message>
  </context>
</TS>
