<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>GHS3D_ADV_ARGS</source>
      <translation>高度な</translation>
    </message>
    <message>
      <source>GHS3D_HYPOTHESIS</source>
      <translation>MG-Tetra</translation>
    </message>
    <message>
      <source>GHS3D_OPTIMIZATIOL_HYPOTHESIS</source>
      <translation>MG-Tetra 最適化</translation>
    </message>
    <message>
      <source>GHS3D_OPTIMIZATIOL_LEVEL</source>
      <translation>最適化のレベル</translation>
    </message>
    <message>
      <source>GHS3D_PERMISSION_DENIED</source>
      <translation>ディレクトリを作成することはできません。</translation>
    </message>
    <message>
      <source>GHS3D_STD_ARGS</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>GHS3D_TITLE</source>
      <translation>仮説の構築</translation>
    </message>
    <message>
      <source>GHS3D_TO_MESH_HOLES</source>
      <translation>メッシュの穴</translation>
    </message>
    <message>
      <source>GHS3D_TO_MAKE_DOMAIN_GROUPS</source>
      <translation>ドメインのグループを確認するには</translation>
    </message>
    <message>
      <source>ADVANCED_MESHING_GROUP_TITLE</source>
      <translation>高度なメッシュ オプション</translation>
    </message>
    <message>
      <source>INIT_MEMORY_SIZE</source>
      <translation>初期メモリのサイズ、</translation>
    </message>
    <message>
      <source>KEEP_WORKING_FILES</source>
      <translation>すべての一時ファイルを保持します。</translation>
    </message>
    <message>
      <source>LEVEL_NONE</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>LEVEL_LIGHT</source>
      <translation>光</translation>
    </message>
    <message>
      <source>LEVEL_MEDIUM</source>
      <translation>(標準) の方法</translation>
    </message>
    <message>
      <source>LEVEL_STANDARDPLUS</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>LEVEL_STRONG</source>
      <translation>砦</translation>
    </message>
    <message>
      <source>LOG_IN_FILE</source>
      <translation>ログ ファイルへの印刷します。</translation>
    </message>
    <message>
      <source>LOG_GROUP_TITLE</source>
      <translation>Et のログをデバッグ</translation>
    </message>
    <message>
      <source>MAX_MEMORY_SIZE</source>
      <translation>最大メモリ サイズ</translation>
    </message>
    <message>
      <source>MEGABYTE</source>
      <translation>メガバイト</translation>
    </message>
    <message>
      <source>MEMORY_GROUP_TITLE</source>
      <translation>メモリの設定</translation>
    </message>
    <message>
      <source>NO_INITIAL_CENTRAL_POINT</source>
      <translation>元の中心点を削除します。</translation>
    </message>
    <message>
      <source>RECOVERY_VERSION</source>
      <translation>バージョン境界の復元を使用します。</translation>
    </message>
    <message>
      <source>FEM_CORRECTION</source>
      <translation>GEF 補正を使用してください。</translation>
    </message>
    <message>
      <source>GHS3D_GRADATION</source>
      <translation>ボリュームのグラデーション</translation>
    </message>
    <message>
      <source>REMOVE_LOG_ON_SUCCESS</source>
      <translation>削除ログ成功</translation>
    </message>
    <message>
      <source>SELECT_DIR</source>
      <translation>...</translation>
    </message>
    <message>
      <source>TEXT_OPTION</source>
      <translation>テキスト オプション</translation>
    </message>
    <message>
      <source>TO_ADD_NODES</source>
      <translation>新しいノードを作成します。</translation>
    </message>
    <message>
      <source>VERBOSE_LEVEL</source>
      <translation>詳細レベル</translation>
    </message>
    <message>
      <source>WORKING_DIR</source>
      <translation>作業ディレクトリ</translation>
    </message>
    <message>
      <source>GHS3D_ENFORCED_VERTICES</source>
      <translation>交差点</translation>
    </message>
    <message>
      <source>GHS3D_ENFORCED_MESHES</source>
      <translation>制約メッシュ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_NAME_COLUMN</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_X_COLUMN</source>
      <translation>X</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Y_COLUMN</source>
      <translation>そこ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Z_COLUMN</source>
      <translation>Z</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SIZE_COLUMN</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_ENTRY_COLUMN</source>
      <translation>ポイント ID</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_COLUMN</source>
      <translation>制約</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_COMPOUND_COLUMN</source>
      <translation>複合</translation>
    </message>
    <message>
      <source>GHS3D_ENF_GROUP_COLUMN</source>
      <translation>グループ</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SELECT_VERTEX</source>
      <translation>・ ポイント (s) の選択</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SELECT_MESH</source>
      <translation>1 つを選択/メッシュ (s)</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_X_LABEL</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Y_LABEL</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_Z_LABEL</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_LABEL</source>
      <translation>制約:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_NODE</source>
      <translation>節点</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_EDGE</source>
      <translation>セグメント</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_CONSTRAINT_FACE</source>
      <translation>Faces</translation>
    </message>
    <message>
      <source>GHS3D_ENF_SIZE_LABEL</source>
      <translation>サイズ:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_GROUP_LABEL</source>
      <translation>グループ:</translation>
    </message>
    <message>
      <source>GHS3D_ENF_ADD</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>GHS3D_ENF_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>GHS3D_ENF_VER_INFO</source>
      <translation>&lt;b&gt;注意&lt;/b&gt;: 交差ポイント関連ジオメトリなしメッシュが考慮されます。</translation>
    </message>
    <message>
      <source>GHS3D_ENF_MESH_INFO</source>
      <translation>&lt;b&gt;注意&lt;/b&gt;: 要素制約の関連付けられたジオメトリなしメッシュ考慮されます。</translation>
    </message>
    <message>
      <source>MODE_SAFE</source>
      <translation>セーフモード</translation>
    </message>
    <message>
      <source>MODE_AGGRESSIVE</source>
      <translation>アグレッシブモード</translation>
    </message>
    <message>
      <source>MODE_NONE</source>
      <translation>無モード</translation>
    </message>
    <message>
      <source>MODE_NO</source>
      <translation>Noモード</translation>
    </message>
    <message>
      <source>MODE_YES</source>
      <translation>Yesモード</translation>
    </message>
    <message>
      <source>MODE_ONLY</source>
      <translation>Onlyモード</translation>
    </message>
    <message>
      <source>GHS3D_OPTIMIZATION</source>
      <translation>最適化</translation>
    </message>
    <message>
      <source>GHS3D_SPLIT_OVERCONSTRAINED</source>
      <translation>過剰拘束要素の分割</translation>
    </message>
    <message>
      <source>GHS3D_PTHREADS_MODE</source>
      <translation>PThreads モード</translation>
    </message>
    <message>
      <source>GHS3D_NB_THREADS</source>
      <translation>最大スレッド数</translation>
    </message>
    <message>
      <source>GHS3D_SMOOTH_OFF_SLIVERS</source>
      <translation>細長い要素のスムーズ化</translation>
    </message>
  </context>
</TS>
