#!/bin/sh
# Copyright (C) 2004-2011  CEA/DEN, EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

rm -rf autom4te.cache aclocal.m4 configure make_config
find . -name "*~" -print -exec rm {} \;
find . -name "*.pyc" -print -exec rm {} \;

find bin -name Makefile.in | xargs rm -f
find idl -name Makefile.in | xargs rm -f
find resources -name Makefile.in | xargs rm -f
find adm_local -name Makefile.in | xargs rm -f
find src -name Makefile.in | xargs rm -f
rm -f adm_local/unix/config_files/config* 
rm -f adm_local/unix/config_files/depcomp
rm -f adm_local/unix/config_files/install-sh 
rm -f adm_local/unix/config_files/libtool.m4 
rm -f adm_local/unix/config_files/ltmain.sh 
rm -f adm_local/unix/config_files/ltoptions.m4 
rm -f adm_local/unix/config_files/ltsugar.m4 
rm -f adm_local/unix/config_files/ltversion.m4 
rm -f adm_local/unix/config_files/lt~obsolete.m4 
rm -f adm_local/unix/config_files/missing 
rm -f Makefile.in
